# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './progressBar.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ProgressBar(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(323, 73)
        Dialog.setStyleSheet("border-radius: 20px;")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        self.frame.setFont(font)
        self.frame.setStyleSheet("border-radius: 4px;\n"
"background: #fff;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 12))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    background-color: rgba(255, 255, 255, 180);\n"
"    border:none;\n"
"    border-radius: 6px;\n"
"    text-align:center;\n"
"     color:#fff;\n"
"}\n"
"QProgressBar::chunk {\n"
"  border-radius: 6px; \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 170, 255, 255), stop:0.99866 rgba(85, 170, 255, 255));\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Loading..."))
